name: Kdru_Guide_app
description: this is the kandahar university Guide App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  lottie: ^2.0.0
  flutter_map: ^6.0.0
  flutter_map_mbtiles: ^1.0.4
  font_awesome_flutter: ^10.8.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  firebase_storage: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
    - assets/fonts/

  fonts:
    - family: PashtoFont
      fonts:
        - asset: assets/fonts/Moon_Dance,Noto_Nastaliq_Urdu/Moon_Dance/MoonDance-Regular.ttf
    - family: pashtoUrd
      fonts:
        - asset: assets/fonts/pashto/NotoNastaliqUrdu-VariableFont_wght.ttf
    - family: pashto
      fonts:
        - asset: assets/fonts/pashto/pashto.ttf

    - family: Noto
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-VariableFont_wght.ttf